### ISSUE TITLE
Error on assigning eventStore to eventBus.publisher

### ISSUE THREAD

**Issue by yauritux** [nordfjord/nestjs-cqrs-es-example-app#1]
get this following error when starting the service:
src/app.module.ts:29:5 - error TS2741: Property 'publish' is missing in type 'EventStore' but required in type 'IEventPublisher<Event<any>>'.

**Comment by nordfjord** [comment]
Hi!

Thanks for raising this 👍!

I've pushed a fix that makes it work again.

If you're looking at using event store with NestJS please consider that this module is using an unsupported TCP client that targets v5 of event store. EventStore has since released a GRPC client which you can read about here: https://developers.eventstore.com/clients/grpc/appending-events/

Consider using this project for inspiration rather than as a dependency
